# Generated by Django 4.1 on 2022-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_question', models.CharField(blank=True, max_length=200, null=True)),
                ('total_marks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
