# Generated by Django 4.1 on 2022-09-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Management', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='branch_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_Management.branch'),
        ),
    ]
