# Generated by Django 4.1 on 2022-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Management', '0010_assigncourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
